# Generated by Django 3.0.8 on 2020-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.TextField(blank=True),
        ),
    ]
