# Generated by Django 3.0.8 on 2020-07-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200716_1519'),
        ('projects', '0002_project_github_link'),
    ]

    operations = [
    ]
