# Generated by Django 3.0.8 on 2020-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200718_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.TextField(help_text='Enter project detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, help_text='Enter project github link', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Enter project name', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateTimeField(help_text='e.g. 2020-07-16 06:35:08'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(help_text='Enter project summary'),
        ),
    ]
